import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

import '../models/speciality.dart';

List spes = [
  "Acupuncturist",
  "Addiction Specialist",
  "Pain Specialist",
  "Allergist",
  "Anatomical Pathologist",
  "Andrologist",
  "Anesthesiologist-Intensivist",
  "Angiologist",
  "Audiologist",
  "Hearing Aid Specialist",
  "Medical Biologist",
  "Oncologist",
  "Cardiologist",
  "Plastic Surgeon",
  "Surgeon",
  "Oral Surgeon",
  "Surgical Oncologist",
  "Hair Transplant Surgeon",
  "Cardiovascular Surgeon",
  "Bariatric Surgeon",
  "Cosmetic Surgeon",
  "General Surgeon",
  "Maxillofacial Surgeon",
  "Orthopedic Traumatologist",
  "Pediatric Surgeon",
  "Thoracic Surgeon",
  "Urologist",
  "Vascular Surgeon",
  "Dentist",
  "Dermatologist",
  "Diabetologist",
  "Dietitian",
  "Embryologist",
  "Endocrinologist",
  "Endocrinologist-Diabetologist",
  "Endodontist",
  "Occupational Therapist",
  "Gynecologist",
  "General Practitioner (GP)",
  "Geneticist",
  "Geriatrician",
  "Hypnotherapist",
  "Hematopathologist",
  "Physical Therapist",
  "Neurosurgeon",
  "Neurologist",
  "Neurophysiologist",
  "Neuropsychiatrist",
  "Neuropsychologist",
  "Pediatric Neurologist",
  "Nutritionist",
  "Nephrologist",
  "Ophthalmologist",
  "Orthodontist",
  "Speech Therapist",
  "Orthoptist",
  "Orthopedic Traumatologist",
  "Osteopath",
  "Otolaryngologist",
  "Periodontist Implantologist",
  "Pharmacist",
  "Clinical Pharmacist",
  "Pharmacologist",
  "Phlebologist",
  "Physiotherapist",
  "Herbalist",
  "Pulmonologist",
  "Podiatrist",
  "Proctologist",
  "Dental Prosthodontist",
  "Psychiatrist",
  "Psychologist",
  "Clinical Psychologist",
  "Psychomotor Therapist",
  "Psychotherapist",
  "Pediatrician",
  "Pediatric Dentist",
  "Child Psychiatrist",
  "Radiologist",
  "Radiation Oncologist",
  "Rheumatologist",
  "Medical Intensivist",
  "Reflexologist",
  "Midwife",
  "Sexologist",
  "Stomatologist",
  "Urodynamic Specialist",
  "Urologist",
  "Veterinarian"
];

List<Speciality> spec = spes.map((value) {
  return Speciality(
    icon: FaIcon(
      FontAwesomeIcons.userDoctor,
      size: 27,
      color: Color(0xFF4163CD),
    ),
    title: value,
  );
}).toList();
