name: tbibi
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  icons_flutter: ^0.0.4
  country_flags: ^2.1.1
  url_launcher: ^6.1.7
  flutter_staggered_animations: ^1.1.1
  fancy_bottom_navigation: ^0.3.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  liquid_pull_to_refresh: ^3.0.1
  rounded_loading_button: ^2.1.0
  flutter_inner_drawer: ^1.0.0+1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  firebase_messaging: ^14.7.3
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.5
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  mailer: ^6.0.1
  flutter_email_sender: ^6.0.2
  image_picker: ^1.0.4
  flutter_rating_bar: ^4.0.0
  permission_handler: ^11.0.1
  intl: ^0.18.1
  dio: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
